# Generated by Django 4.1.7 on 2023-08-06 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_usermessages_replay_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='files',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
