# Generated by Django 4.1.7 on 2023-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_usermessages_files_usermessages_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessages',
            name='files',
        ),
        migrations.AddField(
            model_name='usermessages',
            name='video_file',
            field=models.FileField(null=True, upload_to='video'),
        ),
    ]
