# Generated by Django 4.1.7 on 2023-08-16 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0007_useres_alter_usermessages_send_date_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='userstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_file', models.FileField(upload_to='status')),
                ('status_Date', models.DateField(auto_now_add=True)),
                ('status_Time', models.TimeField(auto_now_add=True)),
                ('duration', models.DurationField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='send_Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='user_status',
        ),
    ]
