# Generated by Django 4.1.7 on 2023-08-17 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0008_userstatus_alter_usermessages_send_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_file', models.FileField(upload_to='status')),
                ('status_time', models.DateTimeField()),
                ('status_end', models.DateTimeField()),
                ('duration', models.DurationField(null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='userstatus',
        ),
    ]
