# Generated by Django 4.2.6 on 2023-12-11 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0010_alter_profile_about_alter_profile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
